(() => {
  const $=id=>document.getElementById(id), escapeHtml=value=>String(value).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
  const state={items:[],query:'',lane:'all',level:'all',alignment:'all',page:1,pageSize:20};
  const speakButton=text=>`<button class="example-speak" type="button" data-speak="${escapeHtml(text)}" title="播放泰文" aria-label="播放泰文">▶ <span>播放</span></button>`;
  const examples=family=>family.member_families.flatMap(member=>member.member_observations.flatMap(obs=>obs.examples.map(example=>({...example,source_book:obs.source_book,source_chapter:obs.source_chapter}))));
  const searchable=family=>`${family.semantic_family_label} ${family.semantic_family_id} ${family.knowledge_lane} ${family.level_floor} ${family.candidate_canonical_target_id} ${family.member_families.flatMap(m=>[m.normalized_label,...m.source_labels]).join(' ')} ${examples(family).flatMap(e=>[e.thai,e.english]).join(' ')}`.toLocaleLowerCase();
  function card(family){const mapped=family.alignment_route==='existing_target', sample=examples(family).slice(0,4), observations=family.member_families.reduce((sum,m)=>sum+m.member_observations.length,0);return `<article class="grammar-card"><div class="grammar-card-head recon-card-head"><div><div class="family-title"><h3>${escapeHtml(family.semantic_family_label)}</h3><span class="kind-badge ${family.knowledge_lane==='grammar'?'grammar':'pattern'}">${escapeHtml(family.knowledge_lane)}</span><span class="mapping-badge ${mapped?'mapped':'deferred'}">${mapped?'mapped candidate':'deferred'}</span></div><div class="family-id">${escapeHtml(family.semantic_family_id)}</div></div></div><div class="source-meta"><span>${escapeHtml(family.level_floor)}</span><span>${family.member_families.length} normalized label${family.member_families.length===1?'':'s'}</span><span>${observations} observation${observations===1?'':'s'}</span><span>${sample.length} of ${examples(family).length} evidence examples shown</span></div><div class="target-box ${mapped?'':'defer'}">${mapped?`Candidate target: <code>${escapeHtml(family.candidate_canonical_target_id)}</code> · ${escapeHtml(family.candidate_relationship)}`:`Not admitted: ${escapeHtml(family.alignment_rationale)}`}</div><div class="example-list">${sample.map(e=>`<div class="example recon-example"><div class="example-thai-row"><p class="thai" lang="th">${escapeHtml(e.thai)}</p>${speakButton(e.thai)}</div><p class="english">${escapeHtml(e.english)}</p><small>Book ${escapeHtml(e.source_book)} · Chapter ${e.source_chapter} · source line ${e.source_line}</small></div>`).join('')}</div><details class="member-summary"><summary>Show ${family.member_families.length} normalized member families</summary><div class="member-list">${family.member_families.map(m=>`<div class="member-item"><h4>${escapeHtml(m.normalized_label)}</h4><div class="relation">${escapeHtml(m.relationship)} · ${m.member_observations.length} observation(s)</div></div>`).join('')}</div></details></article>`}
  function render(){const q=state.query.trim().toLocaleLowerCase();const items=state.items.filter(f=>(state.lane==='all'||f.knowledge_lane===state.lane)&&(state.level==='all'||f.level_floor===state.level)&&(state.alignment==='all'||f.alignment_route===state.alignment)&&(!q||searchable(f).includes(q)));const pages=Math.max(1,Math.ceil(items.length/state.pageSize));state.page=Math.min(state.page,pages);const start=(state.page-1)*state.pageSize;$('reconciliationGrid').innerHTML=items.slice(start,start+state.pageSize).map(card).join('');$('resultLabel').textContent=`${items.length.toLocaleString()} deduplicated families · showing ${items.length?start+1:0}–${Math.min(start+state.pageSize,items.length)}`;$('pagePosition').textContent=`Page ${state.page} of ${pages}`;$('prevPage').disabled=state.page===1;$('nextPage').disabled=state.page===pages;$('emptyState').hidden=items.length>0}
  function reset(){state.page=1;render()}
  fetch('sentence-explorer/canonical-reconciliation-view.v1.json').then(r=>{if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}).then(data=>{state.items=data.semantic_families;$('familyCount').textContent=data.summary.semantic_owner_denominator.toLocaleString();$('mappedCount').textContent=data.summary.mapped_candidates.toLocaleString();$('deferredCount').textContent=data.summary.deferred_alignment.toLocaleString();$('observationCount').textContent=data.summary.source_observations.toLocaleString();[...new Set(state.items.map(x=>x.knowledge_lane))].sort().forEach(lane=>$('laneFilter').insertAdjacentHTML('beforeend',`<option value="${escapeHtml(lane)}">${escapeHtml(lane)}</option>`));render()}).catch(error=>{$('resultLabel').textContent=`Failed to load reconciliation: ${error.message}`});
  $('searchInput').addEventListener('input',e=>{state.query=e.target.value;reset()});$('laneFilter').addEventListener('change',e=>{state.lane=e.target.value;reset()});$('levelFilter').addEventListener('change',e=>{state.level=e.target.value;reset()});$('alignmentFilter').addEventListener('change',e=>{state.alignment=e.target.value;reset()});$('pageSize').addEventListener('change',e=>{state.pageSize=Number(e.target.value);reset()});$('prevPage').addEventListener('click',()=>{state.page--;render()});$('nextPage').addEventListener('click',()=>{state.page++;render()});$('resetButton').addEventListener('click',()=>{Object.assign(state,{query:'',lane:'all',level:'all',alignment:'all',page:1,pageSize:20});['searchInput','laneFilter','levelFilter','alignmentFilter','pageSize'].forEach(id=>$(id).value=id==='searchInput'?'':id==='pageSize'?'20':'all');render()});
  $('reconciliationGrid').addEventListener('click',event=>{const button=event.target.closest('[data-speak]');if(!button)return;if(!('speechSynthesis'in window))return $('speechStatus').textContent='此瀏覽器不支援語音播放。';speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(button.dataset.speak);utterance.lang='th-TH';utterance.rate=.82;speechSynthesis.speak(utterance)});
})();
