(()=>{'use strict';
const data=window.TH_VOCAB_TAXONOMY,$=id=>document.getElementById(id),esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const smallById=new Map(data.small_categories.map(row=>[row.id,row])),bigByNo=new Map(data.big_categories.map(row=>[row.no,row]));
const state={view:'words',big:'all',small:'all',query:'',cefr:'all',pos:'all',classification:'all',i18n:'all',page:1,pageSize:48};
const pill=(value,kind='')=>`<span class="mini-pill ${kind}">${esc(value)}</span>`;
const categoryPill=id=>{const row=smallById.get(id);return pill(row?row.label:id,'primary')};
function wordCard(word){const noPrimary=!word.primary_category_ids.length,unmapped=word.status.includes('reviewed_unmapped'),senses=word.senses.length?`<ul class="sense-list">${word.senses.map(sense=>`<li><strong>Sense ${sense.entry}.${sense.sense}</strong> · ${esc(sense.denotation_en)}${sense.primary_category_id?`<br>${categoryPill(sense.primary_category_id)}`:''}</li>`).join('')}</ul>`:'';return `<article class="word-card"><div class="word-head"><div><h3 class="thai-word" lang="th">${esc(word.lemma)}</h3><div class="word-meta">${pill(word.pos)}${pill(word.cefr)}${pill(word.identity_structure||'baseline')}${noPrimary?pill(unmapped?'reviewed unmapped':'pending','pending'):''}</div></div><span class="word-rank">#${String(word.rank).padStart(4,'0')}</span></div><div class="category-pills">${word.primary_category_ids.map(categoryPill).join('')||pill('尚無 primary','pending')}</div><p class="translation ${word.zh_tw?'':'missing'}">${word.zh_tw?esc(word.zh_tw):'尚無 zh-TW 單字 i18n'}</p>${word.zh_tw_note?`<p class="word-note">${esc(word.zh_tw_note)}</p>`:''}<div class="word-meta">${pill(word.i18n_status,word.zh_tw?'i18n':'pending')} ${pill(word.status)}</div>${senses}</article>`}
function categoryGroups(){return data.big_categories.filter(big=>state.big==='all'||big.no===state.big).map(big=>{const children=data.small_categories.filter(row=>row.big_no===big.no&&(state.small==='all'||row.id===state.small)&&(!state.query||JSON.stringify(row).toLocaleLowerCase().includes(state.query)));return `<article class="category-group"><div class="category-group-head"><div><span class="section-kicker">${big.no} · ${esc(big.id)}</span><h3>${esc(big.label)}</h3><p>${big.small_category_count} 個小分類 · ${big.used_small_category_count} 個目前有 primary membership</p></div><div class="category-big-count"><strong>${big.word_count.toLocaleString()}</strong><small>unique words<br>${big.primary_memberships.toLocaleString()} memberships</small></div></div><div class="small-category-list">${children.map(row=>`<div class="small-category"><button data-small-jump="${esc(row.id)}" type="button">${esc(row.label)}<span>${esc(row.id)}</span></button><strong>${row.word_count}</strong></div>`).join('')}</div></article>`}).join('')}
function searchable(word){return [word.lemma,word.zh_tw,word.zh_tw_note,word.id,word.status,...word.primary_category_ids,...word.secondary_category_ids,...word.senses.map(s=>s.denotation_en)].join(' ').toLocaleLowerCase()}
function filteredWords(){return data.words.filter(word=>{const bigMatch=state.big==='all'||word.primary_category_ids.some(id=>smallById.get(id)?.big_no===state.big),smallMatch=state.small==='all'||word.primary_category_ids.includes(state.small),classMatch=state.classification==='all'||(state.classification==='classified'&&word.classified)||(state.classification==='pending'&&!word.classified&&!word.status.includes('reviewed_unmapped'))||(state.classification==='reviewed_unmapped'&&word.status.includes('reviewed_unmapped')),i18nMatch=state.i18n==='all'||(state.i18n==='present'&&word.zh_tw)||(state.i18n==='missing'&&!word.zh_tw);return bigMatch&&smallMatch&&(state.cefr==='all'||word.cefr===state.cefr)&&(state.pos==='all'||word.pos===state.pos)&&classMatch&&i18nMatch&&(!state.query||searchable(word).includes(state.query))})}
function render(){const isWords=state.view==='words';$('pageSize').parentElement.hidden=!isWords;$('prevPage').hidden=$('nextPage').hidden=$('pagePosition').hidden=!isWords;$('contentGrid').className=isWords?'word-grid':'category-grid';if(!isWords){$('contentGrid').innerHTML=categoryGroups();$('resultLabel').textContent=`${state.big==='all'?data.big_categories.length:1} 個大分類 · ${state.small==='all'?data.small_categories.filter(row=>state.big==='all'||row.big_no===state.big).length:1} 個小分類`;$('emptyState').hidden=Boolean($('contentGrid').innerHTML);return}const words=filteredWords(),pages=Math.max(1,Math.ceil(words.length/state.pageSize));state.page=Math.min(state.page,pages);const start=(state.page-1)*state.pageSize,slice=words.slice(start,start+state.pageSize);$('contentGrid').innerHTML=slice.map(wordCard).join('');$('resultLabel').textContent=`${words.length.toLocaleString()} 個 unique words · 顯示 ${words.length?start+1:0}–${Math.min(start+state.pageSize,words.length)}`;$('pagePosition').textContent=`Page ${state.page} of ${pages}`;$('prevPage').disabled=state.page===1;$('nextPage').disabled=state.page===pages;$('emptyState').hidden=words.length>0}
function fillSelect(id,values,label){$(id).innerHTML=`<option value="all">${label}</option>`+values.map(value=>`<option value="${esc(value)}">${esc(value)}</option>`).join('')}
function refreshSmallOptions(){const rows=data.small_categories.filter(row=>state.big==='all'||row.big_no===state.big);$('smallFilter').innerHTML='<option value="all">全部小分類</option>'+rows.map(row=>`<option value="${esc(row.id)}">${esc(row.label)} (${row.word_count})</option>`).join('');$('smallFilter').value=rows.some(row=>row.id===state.small)?state.small:'all';if($('smallFilter').value==='all')state.small='all'}
function resetPage(){state.page=1;render()}
$('totalWords').textContent=data.summary.total_words.toLocaleString();$('categorizedWords').textContent=data.summary.categorized_words.toLocaleString();$('pendingWords').textContent=data.summary.pending_words.toLocaleString();$('bigCategoryCount').textContent=data.summary.big_categories;$('smallCategoryCount').textContent=data.summary.small_categories;$('i18nCount').textContent=data.summary.zh_tw_i18n.toLocaleString();
$('bigButtons').innerHTML=data.big_categories.map(big=>`<button class="big-button" data-big="${big.no}" type="button"><span>${big.no}</span><strong>${esc(big.label)}</strong><small>${big.word_count}</small></button>`).join('');fillSelect('cefrFilter',[...new Set(data.words.map(word=>word.cefr))].sort(),'全部 CEFR');fillSelect('posFilter',[...new Set(data.words.map(word=>word.pos))].sort(),'全部詞性');refreshSmallOptions();
document.querySelectorAll('[data-big]').forEach(button=>button.addEventListener('click',()=>{state.big=button.dataset.big;state.small='all';state.page=1;document.querySelectorAll('[data-big]').forEach(item=>item.classList.toggle('active',item===button));refreshSmallOptions();$('panelTitle').textContent=state.big==='all'?'全部字庫':bigByNo.get(state.big).label;render()}));
document.querySelectorAll('[data-view]').forEach(button=>button.addEventListener('click',()=>{state.view=button.dataset.view;state.page=1;document.querySelectorAll('[data-view]').forEach(item=>item.classList.toggle('active',item===button));render()}));
$('searchInput').addEventListener('input',event=>{state.query=event.target.value.trim().toLocaleLowerCase();resetPage()});$('smallFilter').addEventListener('change',event=>{state.small=event.target.value;resetPage()});$('cefrFilter').addEventListener('change',event=>{state.cefr=event.target.value;resetPage()});$('posFilter').addEventListener('change',event=>{state.pos=event.target.value;resetPage()});$('classFilter').addEventListener('change',event=>{state.classification=event.target.value;resetPage()});$('i18nFilter').addEventListener('change',event=>{state.i18n=event.target.value;resetPage()});$('pageSize').addEventListener('change',event=>{state.pageSize=Number(event.target.value);resetPage()});$('prevPage').addEventListener('click',()=>{state.page--;render();scrollTo({top:document.querySelector('.vocab-panel').offsetTop-12,behavior:'smooth'})});$('nextPage').addEventListener('click',()=>{state.page++;render();scrollTo({top:document.querySelector('.vocab-panel').offsetTop-12,behavior:'smooth'})});
$('contentGrid').addEventListener('click',event=>{const button=event.target.closest('[data-small-jump]');if(!button)return;state.view='words';state.small=button.dataset.smallJump;state.big=smallById.get(state.small).big_no;state.page=1;document.querySelectorAll('[data-view]').forEach(item=>item.classList.toggle('active',item.dataset.view==='words'));document.querySelectorAll('[data-big]').forEach(item=>item.classList.toggle('active',item.dataset.big===state.big));refreshSmallOptions();$('smallFilter').value=state.small;$('panelTitle').textContent=smallById.get(state.small).label;render()});
$('resetButton').addEventListener('click',()=>{Object.assign(state,{view:'words',big:'all',small:'all',query:'',cefr:'all',pos:'all',classification:'all',i18n:'all',page:1,pageSize:48});document.querySelectorAll('input').forEach(input=>input.value='');['cefrFilter','posFilter','classFilter','i18nFilter'].forEach(id=>$(id).value='all');$('pageSize').value='48';document.querySelectorAll('[data-big]').forEach(button=>button.classList.toggle('active',button.dataset.big==='all'));document.querySelectorAll('[data-view]').forEach(button=>button.classList.toggle('active',button.dataset.view==='words'));refreshSmallOptions();$('panelTitle').textContent='全部字庫';render()});
render();
})();
